---

# global settings
image: alpine:latest
before_script: &global_before_scripts
  - apk upgrade -U
after_script:
  - .ci/lib/move_logs.sh $CI_PROJECT_DIR
stages:
  - lint
variables:
  # Default of 20 is pretty small, sometimes MRs have >20 commits in them. 100
  # seems like a reasonable balance. If this is too low, git merge-base (from ci/
  # common.py) can fail
  GIT_DEPTH: 100
  URL: "https://download.kde.org/stable/plasma/6.2.2/kscreenlocker-6.2.2.tar.xz"
  
# This defines the rules for when a pipeline should run.
workflow:
  rules:
    # Don't run branch pipeline if an MR is open (only the MR pipeline will run)
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    # Run for merge requests
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Run scheduled pipeline for autoupdate or manually triggered pipeline
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web"

dl_test:
  stage: lint
  script:
    -  apk add curl bind-tools iproute2-minimal wget
    - cat /etc/resolv.conf
    - nslookup postmarketos.org
    - nslookup alpinelinux.org
    - ip -br a

    - wget --no-dns-cache --verbose $URL
    - wget --no-dns-cache --verbose $URL
    - wget --no-dns-cache --verbose $URL
    - wget --no-dns-cache --verbose $URL
    - wget --no-dns-cache --verbose $URL
    - wget --no-dns-cache --verbose $URL
    - wget --no-dns-cache --verbose $URL
    - wget --no-dns-cache --verbose $URL
    - curl --dns-servers 140.211.166.130 --verbose --max-time 10 $URL
    - curl --dns-servers 140.211.166.130 --verbose --max-time 10 $URL
    - curl --dns-servers 140.211.166.130 --verbose --max-time 10 $URL
    - curl --dns-servers 140.211.166.130 --verbose --max-time 10 $URL
    - curl --dns-servers 140.211.166.130 --verbose --max-time 10 $URL
    - curl --dns-servers 140.211.166.130 --verbose --max-time 10 $URL
    - curl --dns-servers 140.211.166.130 --verbose --max-time 10 $URL
    - curl --dns-servers 140.211.166.130 --verbose --max-time 10 $URL
    - curl --dns-servers 140.211.166.130 --verbose --max-time 10 $URL
    - curl --dns-servers 140.211.166.130 --verbose --max-time 10 $URL
    - curl --dns-servers 140.211.166.130 --verbose --max-time 10 $URL
    - curl --dns-servers 140.211.166.130 --verbose --max-time 10 $URL
